# -*- coding: utf-8 -*-
"""AgroDetect AI

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Hj7lOTKhNvn_3UcpXl4U7s_RSONRIn--

Install packages
"""

# =========================================================
# AGRODETECT AI
# PART 1 — INSTALLATION
# =========================================================

!pip install -q -U \
    langchain \
    langgraph \
    langchain-groq \
    "mcp[cli]" \
    pandas \
    numpy \
    scikit-learn \
    matplotlib

"""Imports"""

# =========================================================
# IMPORTS
# =========================================================

import os
import json
import warnings

import pandas as pd
import numpy as np

from IPython.display import display, Markdown

warnings.filterwarnings("ignore")

print("✅ AgroDetect AI libraries loaded")

"""Load Groq"""

# =========================================================
# GROQ API KEY
# =========================================================

from google.colab import userdata

GROQ_API_KEY = userdata.get("GROQ_API_KEY")

if not GROQ_API_KEY:
    raise ValueError(
        "❌ GROQ_API_KEY not found in Colab Secrets"
    )

os.environ["GROQ_API_KEY"] = GROQ_API_KEY

print("✅ Groq API key loaded")

"""Initialize Groq LLM"""

# =========================================================
# GROQ LLM
# =========================================================

from langchain_groq import ChatGroq

llm = ChatGroq(
    model="llama-3.3-70b-versatile",
    temperature=0
)

print("✅ Groq LLM initialized")

"""Test Groq"""

# =========================================================
# TEST GROQ
# =========================================================

response = llm.invoke(
    "You are AgroDetect AI. "
    "Reply with exactly: AgroDetect AI is ready."
)

print(response.content)

"""Test LangGraph"""

# =========================================================
# LANGGRAPH TEST
# =========================================================

from typing import TypedDict

from langgraph.graph import (
    StateGraph,
    START,
    END
)


class AgroState(TypedDict):
    message: str


def agro_test_agent(state: AgroState):

    response = llm.invoke(
        "Say: AgroDetect AI LangGraph workflow is ready."
    )

    return {
        "message": response.content
    }


builder = StateGraph(AgroState)

builder.add_node(
    "agro_test_agent",
    agro_test_agent
)

builder.add_edge(
    START,
    "agro_test_agent"
)

builder.add_edge(
    "agro_test_agent",
    END
)

agro_graph = builder.compile()

result = agro_graph.invoke({
    "message": ""
})

print(result["message"])

"""Create MCP Server"""

# =========================================================
# MCP SERVER
# =========================================================

from mcp.server import MCPServer
from mcp import Client

mcp = MCPServer(
    "AgroDetect MCP Server"
)

print("✅ AgroDetect MCP Server created")

"""Create first MCP tool"""

# =========================================================
# MCP TOOL — SYSTEM STATUS
# =========================================================

@mcp.tool()
def agro_system_status() -> str:
    """
    Check whether AgroDetect AI MCP system is ready.
    """

    return json.dumps({
        "project": "AgroDetect AI",
        "status": "ready",
        "llm": "Groq",
        "framework": "LangChain + LangGraph",
        "protocol": "MCP",
        "domain": "Agricultural Intelligence"
    })

print("✅ MCP tool registered: agro_system_status")

"""Test MCP Client"""

# =========================================================
# MCP CLIENT TEST
# =========================================================

async with Client(mcp) as client:

    tools = await client.list_tools()

    print("====================================")
    print("AVAILABLE MCP TOOLS")
    print("====================================")

    for tool in tools.tools:
        print("•", tool.name)

    result = await client.call_tool(
        "agro_system_status",
        {}
    )

    print("\n====================================")
    print("MCP RESULT")
    print("====================================")

    # Show only clean tool output
    print(result.content[0].text)

"""AgroDetect AI
                       │
                       ↓
                  Groq LLM
                       │
                       ↓
                  LangChain
                       │
                       ↓
                  LangGraph
                       │
                       ↓
                  MCP Client
                       │
                       ↓
                  MCP Server
                       │
                       ↓
             agro_system_status()

Upload
"""

from google.colab import files

uploaded = files.upload()

"""Set the path"""

# =========================================================
# AGRICULTURAL DATASET
# =========================================================

CSV_PATH = "/content/agricultural.csv"

print("Dataset:", CSV_PATH)

"""Load and inspect"""

# =========================================================
# LOAD AGRICULTURAL DATA
# =========================================================

df = pd.read_csv(CSV_PATH)

print("✅ Agricultural dataset loaded")
print()
print("Rows    :", len(df))
print("Columns :", len(df.columns))

print("\nColumn names:")
for col in df.columns:
    print("•", col)

display(df.head())

"""Create MCP Dataset Summary Tool"""

# =========================================================
# MCP TOOL 1 → DATASET SUMMARY
# =========================================================

@mcp.tool()
def get_crop_dataset_summary() -> str:
    """Return basic information about the agricultural dataset."""

    data = pd.read_csv(CSV_PATH)

    result = {
        "Dataset": "agricultural.csv",
        "Total Records": int(len(data)),
        "Total Columns": int(len(data.columns)),
        "Columns": list(data.columns),
        "Missing Values": int(data.isna().sum().sum()),
        "Duplicate Rows": int(data.duplicated().sum())
    }

    return json.dumps(result, indent=2)

print("✅ MCP tool registered")

"""Create MCP Crop Statistics Tool"""

# =========================================================
# MCP TOOL 2 → CROP STATISTICS
# =========================================================

@mcp.tool()
def get_crop_statistics() -> str:
    """Return numerical statistics from the agricultural dataset."""

    data = pd.read_csv(CSV_PATH)

    numeric_columns = data.select_dtypes(
        include=np.number
    ).columns

    statistics = {}

    for column in numeric_columns:

        statistics[column] = {
            "mean": round(float(data[column].mean()), 2),
            "minimum": round(float(data[column].min()), 2),
            "maximum": round(float(data[column].max()), 2)
        }

    return json.dumps(statistics, indent=2)

print("✅ MCP statistics tool registered")

"""Create MCP Missing-Value Tool"""

# =========================================================
# MCP TOOL 3 → DATA QUALITY
# =========================================================

@mcp.tool()
def get_missing_value_analysis() -> str:
    """Identify missing values in agricultural data."""

    data = pd.read_csv(CSV_PATH)

    missing = data.isna().sum()

    result = {
        column: int(count)
        for column, count in missing.items()
        if count > 0
    }

    return json.dumps(result, indent=2)

print("✅ MCP data-quality tool registered")

"""Check MCP Tools"""

# =========================================================
# MCP TOOL DISCOVERY
# =========================================================

async with Client(mcp) as client:

    tools = await client.list_tools()

    print("====================================")
    print("AGRODETECT MCP TOOLS")
    print("====================================")

    for tool in tools.tools:
        print("•", tool.name)

"""Call Dataset Summary"""

# =========================================================
# TEST DATASET SUMMARY
# =========================================================

async with Client(mcp) as client:

    result = await client.call_tool(
        "get_crop_dataset_summary",
        {}
    )

    print(result.content[0].text)

"""Call Data Quality Tool"""

# =========================================================
# TEST DATA QUALITY
# =========================================================

async with Client(mcp) as client:

    result = await client.call_tool(
        "get_missing_value_analysis",
        {}
    )

    print(result.content[0].text)

"""MCP agricultural data layer:


                    agricultural.csv
                            ↓
                      MCP Server
                            ↓
              ┌────────────┼────────────┐
              ↓            ↓            ↓
          Dataset       Statistics   Data Quality
          Summary                       ↓
              └────────────┼────────────┘
                            ↓
                      MCP Client

Create the Data Analyst Agent
"""

# =========================================================
# AGRODETECT AI
# PART 3 — DATA ANALYST AGENT
# =========================================================

from typing import TypedDict


class AgroState(TypedDict, total=False):
    user_question: str
    dataset_summary: str
    statistics: str
    missing_values: str
    analysis: str


async def data_analyst_agent(state: AgroState):

    print("\n🔍 DATA ANALYST AGENT")
    print("Getting agricultural data from MCP...")

    # -----------------------------------------------------
    # MCP CLIENT
    # -----------------------------------------------------

    async with Client(mcp) as client:

        summary_result = await client.call_tool(
            "get_crop_dataset_summary",
            {}
        )

        statistics_result = await client.call_tool(
            "get_crop_statistics",
            {}
        )

        missing_result = await client.call_tool(
            "get_missing_value_analysis",
            {}
        )

    # -----------------------------------------------------
    # EXTRACT CLEAN MCP RESULTS
    # -----------------------------------------------------

    summary = summary_result.content[0].text
    statistics = statistics_result.content[0].text
    missing = missing_result.content[0].text

    print("✅ MCP data received")

    # -----------------------------------------------------
    # GROQ ANALYSIS
    # -----------------------------------------------------

    prompt = f"""
You are the Data Analyst Agent for AgroDetect AI.

Analyze the agricultural dataset using ONLY the information
provided below.

DATASET SUMMARY:
{summary}

NUMERICAL STATISTICS:
{statistics}

MISSING VALUES:
{missing}

Determine:

1. Total records
2. Important numerical variables
3. Important categorical variables
4. Possible target variable
5. Missing-value issues
6. Important agricultural variables
7. Recommended next analysis

Do not invent information.

Give a clear professional analysis.
"""

    response = llm.invoke(prompt)

    print("✅ Groq analysis completed")

    return {
        "dataset_summary": summary,
        "statistics": statistics,
        "missing_values": missing,
        "analysis": response.content
    }

"""Test the DATA ANALYST AGENT"""

# =========================================================
# TEST DATA ANALYST AGENT
# =========================================================

state = {
    "user_question": "Analyze my agricultural dataset."
}

result = await data_analyst_agent(state)

print("\n")
print("=" * 60)
print("AGRODETECT AI — DATA ANALYSIS")
print("=" * 60)

print(result["analysis"])

"""Connect Agent to LangGraph

Now we put the agent into our actual workflow.
"""

# =========================================================
# LANGGRAPH — DATA ANALYST WORKFLOW
# =========================================================

from langgraph.graph import StateGraph, START, END


graph_builder = StateGraph(AgroState)

graph_builder.add_node(
    "data_analyst",
    data_analyst_agent
)

graph_builder.add_edge(
    START,
    "data_analyst"
)

graph_builder.add_edge(
    "data_analyst",
    END
)

data_analysis_graph = graph_builder.compile()

print("✅ LangGraph Data Analyst workflow created")

"""Run LangGraph"""

# =========================================================
# RUN LANGGRAPH
# =========================================================

final_state = await data_analysis_graph.ainvoke({
    "user_question": "Analyze the agricultural dataset."
})

print("\n")
print("=" * 60)
print("🌾 AGRODETECT AI")
print("=" * 60)

print(final_state["analysis"])

"""🌾 User
                          ↓
                    LangGraph
                          ↓
                Data Analyst Agent
                          ↓
                    MCP Client
                          ↓
                    MCP Server
                          ↓
            ┌────────────┼─────────────┐
            ↓            ↓             ↓
        Summary      Statistics    Missing Values
            └────────────┼─────────────┘
                          ↓
                      Groq LLM
                          ↓
                  Data Understanding

The agent doesn't directly read the CSV.

Instead:

Agent → MCP → Data Tools → Results → Groq → Analysis

Create Planner Agent
"""

# =========================================================
# PLANNER AGENT
# =========================================================

async def planner_agent(state: AgroState):

    print("\n🧠 PLANNER AGENT")
    print("Creating agricultural investigation plan...")

    question = state.get(
        "user_question",
        "Analyze the agricultural dataset."
    )

    prompt = f"""
You are the Planner Agent of AgroDetect AI.

Your job is to create an investigation plan for an
agricultural data analysis problem.

USER QUESTION:
{question}

Create a practical step-by-step investigation plan.

The plan may include:

- regional comparison
- crop comparison
- rainfall analysis
- soil moisture analysis
- fertilizer analysis
- irrigation analysis
- temperature analysis
- pest analysis
- yield comparison
- anomaly detection
- statistical relationships

Do NOT perform the analysis yet.

Do NOT generate Python code.

Only create the investigation plan.

Return 5 to 8 clear steps.
"""

    response = llm.invoke(prompt)

    plan = response.content

    print("✅ Investigation plan created")

    return {
        "analysis_plan": plan
    }

"""Test Planner Agent"""

# =========================================================
# TEST PLANNER AGENT
# =========================================================

planner_result = await planner_agent({
    "user_question":
        "Why is crop yield lower in some regions?"
})

print("\n")
print("=" * 60)
print("🌾 AGRODETECT AI — INVESTIGATION PLAN")
print("=" * 60)

print(planner_result["analysis_plan"])

"""Connect Planner + Data Analyst with LangGraph"""

# =========================================================
# LANGGRAPH — PLANNER → DATA ANALYST
# =========================================================

from langgraph.graph import StateGraph, START, END


graph_builder = StateGraph(AgroState)


graph_builder.add_node(
    "planner",
    planner_agent
)

graph_builder.add_node(
    "data_analyst",
    data_analyst_agent
)


# START → Planner
graph_builder.add_edge(
    START,
    "planner"
)


# Planner → Data Analyst
graph_builder.add_edge(
    "planner",
    "data_analyst"
)


# Data Analyst → END
graph_builder.add_edge(
    "data_analyst",
    END
)


agro_graph = graph_builder.compile()

print("✅ AgroDetect LangGraph created")

# =========================================================
# AGRODETECT AI — SHARED STATE
# =========================================================

from typing import TypedDict


class AgroState(TypedDict, total=False):

    user_question: str

    analysis_plan: str

    dataset_summary: str
    statistics: str
    missing_values: str

    analysis: str

# =========================================================
# PLANNER AGENT
# =========================================================

async def planner_agent(state: AgroState):

    print("\n🧠 PLANNER AGENT")
    print("Creating agricultural investigation plan...")

    question = state.get(
        "user_question",
        "Analyze the agricultural dataset."
    )

    prompt = f"""
You are the Planner Agent of AgroDetect AI.

User question:
{question}

Create an agricultural data investigation plan.

Include 5 to 8 practical steps.

Possible areas:
- crop comparison
- regional comparison
- rainfall
- soil moisture
- fertilizer
- irrigation
- temperature
- pest level
- crop yield
- anomalies
- relationships between variables

Do not generate Python code.
Do not perform the analysis.

Return only the investigation plan.
"""

    response = llm.invoke(prompt)

    plan = response.content

    print("✅ Investigation plan created")

    # IMPORTANT:
    # Return the SAME key defined in AgroState
    return {
        "analysis_plan": plan
    }

# =========================================================
# DATA ANALYST AGENT
# =========================================================

async def data_analyst_agent(state: AgroState):

    print("\n🔍 DATA ANALYST AGENT")
    print("Getting agricultural data from MCP...")

    async with Client(mcp) as client:

        summary_result = await client.call_tool(
            "get_crop_dataset_summary",
            {}
        )

        statistics_result = await client.call_tool(
            "get_crop_statistics",
            {}
        )

        missing_result = await client.call_tool(
            "get_missing_value_analysis",
            {}
        )

    summary = summary_result.content[0].text
    statistics = statistics_result.content[0].text
    missing = missing_result.content[0].text

    print("✅ MCP data received")

    prompt = f"""
You are the Data Analyst Agent for AgroDetect AI.

Analyze the agricultural dataset.

DATASET SUMMARY:
{summary}

NUMERICAL STATISTICS:
{statistics}

MISSING VALUES:
{missing}

USER QUESTION:
{state.get("user_question", "")}

INVESTIGATION PLAN:
{state.get("analysis_plan", "")}

Determine:

1. Dataset size
2. Numerical variables
3. Categorical variables
4. Possible target variable
5. Missing-value issues
6. Important agricultural variables
7. Recommended analytical direction

Do not invent information.

Return a clear professional analysis.
"""

    response = llm.invoke(prompt)

    print("✅ Groq analysis completed")

    return {
        "dataset_summary": summary,
        "statistics": statistics,
        "missing_values": missing,
        "analysis": response.content
    }

# =========================================================
# REBUILD AGRODETECT LANGGRAPH
# =========================================================

from langgraph.graph import StateGraph, START, END


graph_builder = StateGraph(AgroState)


graph_builder.add_node(
    "planner",
    planner_agent
)

graph_builder.add_node(
    "data_analyst",
    data_analyst_agent
)


graph_builder.add_edge(
    START,
    "planner"
)

graph_builder.add_edge(
    "planner",
    "data_analyst"
)

graph_builder.add_edge(
    "data_analyst",
    END
)


agro_graph = graph_builder.compile()

print("✅ LangGraph rebuilt successfully")

"""Run the workflow"""

# =========================================================
# RUN AGRODETECT
# =========================================================

final_state = await agro_graph.ainvoke({

    "user_question":
        "Why is crop yield lower in some regions?"
})


print("\n")
print("=" * 70)
print("🌾 AGRODETECT AI")
print("=" * 70)


print("\n🧠 INVESTIGATION PLAN")
print("-" * 70)

print(
    final_state.get(
        "analysis_plan",
        "No investigation plan returned."
    )
)


print("\n🔍 DATA ANALYSIS")
print("-" * 70)

print(
    final_state.get(
        "analysis",
        "No analysis returned."
    )
)

"""Add coding fields to State"""

# =========================================================
# AGRODETECT AI — UPDATED STATE
# =========================================================

from typing import TypedDict


class AgroState(TypedDict, total=False):

    user_question: str

    analysis_plan: str

    dataset_summary: str
    statistics: str
    missing_values: str

    analysis: str

    generated_code: str
    code_result: str

"""Create MCP Python Analysis Tool

This tool receives Python code generated by the Coding Agent.
"""

# =========================================================
# MCP TOOL → PYTHON ANALYSIS
# =========================================================

@mcp.tool()
def execute_agricultural_analysis(code: str) -> str:
    """
    Execute controlled Python analysis against agricultural data.
    The dataframe is available as variable: df
    """

    try:

        data = pd.read_csv(CSV_PATH)

        # Controlled execution environment
        allowed_globals = {
            "pd": pd,
            "np": np,
            "df": data
        }

        local_vars = {}

        exec(
            code,
            allowed_globals,
            local_vars
        )

        # Find the result created by the code
        if "result" in local_vars:

            output = local_vars["result"]

        else:

            output = "Code executed successfully, but no 'result' variable was created."

        # Convert pandas/numpy objects to readable text
        if isinstance(output, (pd.DataFrame, pd.Series)):
            output = output.to_string()

        else:
            output = str(output)

        return output

    except Exception as e:

        return f"ERROR: {type(e).__name__}: {str(e)}"

"""Create Coding Agent"""

# =========================================================
# CODING AGENT
# =========================================================

async def coding_agent(state: AgroState):

    print("\n👨‍💻 CODING AGENT")
    print("Generating agricultural analysis code...")

    question = state.get(
        "user_question",
        ""
    )

    plan = state.get(
        "analysis_plan",
        ""
    )

    summary = state.get(
        "dataset_summary",
        ""
    )

    prompt = f"""
You are the Coding Agent for AgroDetect AI.

Your job is to write Python code that analyzes the
agricultural dataset.

USER QUESTION:
{question}

INVESTIGATION PLAN:
{plan}

DATASET INFORMATION:
{summary}

The dataframe is already available as:

df

Available libraries:

pd
np

Write Python code that performs useful analysis
according to the investigation plan.

IMPORTANT RULES:

1. Do not load the CSV.
2. Do not use file operations.
3. Do not import libraries.
4. The dataframe is already available as df.
5. Store the final result in a variable called `result`.
6. Use pandas/numpy only.
7. Return ONLY Python code.
8. Do not use markdown code fences.
"""

    response = llm.invoke(prompt)

    code = response.content.strip()

    # Remove accidental markdown fences
    code = code.replace("```python", "")
    code = code.replace("```", "")
    code = code.strip()

    print("✅ Python analysis code generated")

    return {
        "generated_code": code
    }

"""Test Coding Agent"""

# =========================================================
# TEST CODING AGENT
# =========================================================

coding_test_state = {
    "user_question":
        "Why is crop yield lower in some regions?",

    "analysis_plan":
        """
        1. Compare average crop yield by region.
        2. Identify low-yield regions.
        3. Compare rainfall.
        4. Compare soil moisture.
        5. Compare fertilizer.
        6. Analyze irrigation.
        7. Analyze pest level.
        """,

    "dataset_summary":
        final_state.get(
            "dataset_summary",
            ""
        )
}

coding_result = await coding_agent(
    coding_test_state
)

print("\n")
print("=" * 70)
print("GENERATED PYTHON CODE")
print("=" * 70)

print(coding_result["generated_code"])

"""Test the MCP execution tool

Now send the generated code to MCP.
"""

# =========================================================
# TEST MCP PYTHON EXECUTION
# =========================================================

async with Client(mcp) as client:

    result = await client.call_tool(
        "execute_agricultural_analysis",
        {
            "code": coding_result["generated_code"]
        }
    )

    execution_output = result.content[0].text

print("\n")
print("=" * 70)
print("MCP CODE EXECUTION RESULT")
print("=" * 70)

print(execution_output)

"""Update LangGraph"""

# =========================================================
# LANGGRAPH — ADD CODING AGENT
# =========================================================

from langgraph.graph import StateGraph, START, END


graph_builder = StateGraph(AgroState)


graph_builder.add_node(
    "planner",
    planner_agent
)

graph_builder.add_node(
    "data_analyst",
    data_analyst_agent
)

graph_builder.add_node(
    "coding_agent",
    coding_agent
)


graph_builder.add_edge(
    START,
    "planner"
)

graph_builder.add_edge(
    "planner",
    "data_analyst"
)

graph_builder.add_edge(
    "data_analyst",
    "coding_agent"
)

graph_builder.add_edge(
    "coding_agent",
    END
)


agro_graph = graph_builder.compile()

print("✅ LangGraph updated")

"""Planner
        ↓
      Data Analyst
        ↓
      Coding Agent

Run the workflow
"""

# =========================================================
# RUN AGRODETECT — PART 5
# =========================================================

final_state = await agro_graph.ainvoke({

    "user_question":
        "Why is crop yield lower in some regions?"
})


print("\n")
print("=" * 70)
print("🌾 AGRODETECT AI")
print("=" * 70)


print("\n🧠 INVESTIGATION PLAN")
print("-" * 70)

print(
    final_state.get(
        "analysis_plan",
        "No plan"
    )
)


print("\n🔍 DATA ANALYSIS")
print("-" * 70)

print(
    final_state.get(
        "analysis",
        "No analysis"
    )
)


print("\n👨‍💻 GENERATED CODE")
print("-" * 70)

print(
    final_state.get(
        "generated_code",
        "No code generated"
    )
)

"""Autonomous Debugging Agent

Now we add the Coding Agent + Debugging Agent loop.

This is the important autonomous part:

Planner
        ↓
      Data Analyst
        ↓
      Coding Agent
        ↓
      Generate Python
        ↓
      MCP Execution
        ↓
      Success?
      ┌─┴───────┐
      YES       NO
      ↓         ↓
      Continue  Debugging Agent
                  ↓
              Fix Code
                  ↓
              MCP Execute
                  ↓
                Retry

Update the State
"""

# =========================================================
# AGRODETECT AI — PART 6 STATE
# =========================================================

from typing import TypedDict


class AgroState(TypedDict, total=False):

    user_question: str

    analysis_plan: str

    dataset_summary: str
    statistics: str
    missing_values: str

    analysis: str

    generated_code: str
    code_result: str

    error_message: str

    retry_count: int
    max_retries: int

    final_status: str

"""Create MCP Execution Helper

We already have the MCP tool:

execute_agricultural_analysis

Now create a reusable function for our agents.
"""

# =========================================================
# MCP CODE EXECUTION HELPER
# =========================================================

async def execute_code_with_mcp(code: str):

    async with Client(mcp) as client:

        result = await client.call_tool(
            "execute_agricultural_analysis",
            {
                "code": code
            }
        )

    return result.content[0].text

"""Create Debugging Agent

The Debugging Agent receives:

original question
investigation plan
failed Python code
error message

Then Groq generates corrected code.
"""

# =========================================================
# DEBUGGING AGENT
# =========================================================

async def debugging_agent(state: AgroState):

    print("\n🛠️ DEBUGGING AGENT")

    error = state.get(
        "error_message",
        ""
    )

    old_code = state.get(
        "generated_code",
        ""
    )

    question = state.get(
        "user_question",
        ""
    )

    plan = state.get(
        "analysis_plan",
        ""
    )

    retry_count = state.get(
        "retry_count",
        0
    )

    print(
        f"Attempt {retry_count + 1}: "
        "Diagnosing Python error..."
    )

    prompt = f"""
You are the Autonomous Debugging Agent
for AgroDetect AI.

The Coding Agent generated Python code,
but execution failed.

USER QUESTION:
{question}

INVESTIGATION PLAN:
{plan}

FAILED CODE:
{old_code}

ERROR:
{error}

Your task:

1. Understand the error.
2. Identify the cause.
3. Correct the Python code.
4. Return ONLY corrected Python code.

Rules:

- The dataframe is already available as `df`.
- Available libraries are `pd` and `np`.
- Do not load the CSV.
- Do not use file operations.
- Do not import libraries.
- Store the final answer in a variable called `result`.
- Return ONLY Python code.
"""

    response = llm.invoke(prompt)

    corrected_code = response.content.strip()

    corrected_code = corrected_code.replace(
        "```python",
        ""
    )

    corrected_code = corrected_code.replace(
        "```",
        ""
    )

    corrected_code = corrected_code.strip()

    print("✅ Debugging Agent generated corrected code")

    return {
        "generated_code": corrected_code
    }

"""Create Execution Node

This node sends the generated code to the MCP server.
"""

# =========================================================
# CODE EXECUTION NODE
# =========================================================

async def code_execution_node(state: AgroState):

    print("\n⚙️ MCP CODE EXECUTION")

    code = state.get(
        "generated_code",
        ""
    )

    retry_count = state.get(
        "retry_count",
        0
    )

    output = await execute_code_with_mcp(code)

    # -----------------------------------------------------
    # Check whether execution failed
    # -----------------------------------------------------

    if output.startswith("ERROR:"):

        print("❌ Code execution failed")

        print("\nError:")
        print(output)

        return {
            "code_result": "",
            "error_message": output,
            "retry_count": retry_count + 1,
            "final_status": "error"
        }

    # -----------------------------------------------------
    # Successful execution
    # -----------------------------------------------------

    print("✅ Code executed successfully")

    return {
        "code_result": output,
        "error_message": "",
        "final_status": "success"
    }

"""Create Conditional Routing

This is the important LangGraph decision.
"""

# =========================================================
# DEBUG ROUTER
# =========================================================

def debug_router(state: AgroState):

    status = state.get(
        "final_status",
        ""
    )

    retry_count = state.get(
        "retry_count",
        0
    )

    max_retries = state.get(
        "max_retries",
        3
    )

    # Successful execution
    if status == "success":

        return "success"

    # Retry if attempts remain
    if retry_count < max_retries:

        return "debug"

    # Stop safely
    return "stop"

"""Success
          ↓
        Continue

        Error + retries remaining
          ↓
        Debug

        Error + 3 attempts reached
          ↓
        Stop safely

Build the Autonomous LangGraph
"""

# =========================================================
# AGRODETECT AUTONOMOUS CODING GRAPH
# =========================================================

from langgraph.graph import (
    StateGraph,
    START,
    END
)


graph_builder = StateGraph(AgroState)


# ---------------------------------------------------------
# Nodes
# ---------------------------------------------------------

graph_builder.add_node(
    "planner",
    planner_agent
)

graph_builder.add_node(
    "data_analyst",
    data_analyst_agent
)

graph_builder.add_node(
    "coding_agent",
    coding_agent
)

graph_builder.add_node(
    "execute_code",
    code_execution_node
)

graph_builder.add_node(
    "debugging_agent",
    debugging_agent
)


# ---------------------------------------------------------
# Main flow
# ---------------------------------------------------------

graph_builder.add_edge(
    START,
    "planner"
)

graph_builder.add_edge(
    "planner",
    "data_analyst"
)

graph_builder.add_edge(
    "data_analyst",
    "coding_agent"
)

graph_builder.add_edge(
    "coding_agent",
    "execute_code"
)


# ---------------------------------------------------------
# Conditional execution
# ---------------------------------------------------------

graph_builder.add_conditional_edges(

    "execute_code",

    debug_router,

    {
        "success": END,
        "debug": "debugging_agent",
        "stop": END
    }
)


# ---------------------------------------------------------
# Debug → Execute again
# ---------------------------------------------------------

graph_builder.add_edge(
    "debugging_agent",
    "execute_code"
)


agro_graph = graph_builder.compile()


print("✅ Autonomous AgroDetect LangGraph created")

"""Run the complete workflow"""

# =========================================================
# RUN AGRODETECT AI
# =========================================================

final_state = await agro_graph.ainvoke({

    "user_question":
        "Why is crop yield lower in some regions?",

    "retry_count": 0,

    "max_retries": 3
})


print("\n")
print("=" * 75)
print("🌾 AGRODETECT AI — FINAL RESULT")
print("=" * 75)


print("\n🧠 INVESTIGATION PLAN")
print("-" * 75)

print(
    final_state.get(
        "analysis_plan",
        "Not available"
    )
)


print("\n🔍 DATA ANALYSIS")
print("-" * 75)

print(
    final_state.get(
        "analysis",
        "Not available"
    )
)


print("\n👨‍💻 GENERATED CODE")
print("-" * 75)

print(
    final_state.get(
        "generated_code",
        "Not available"
    )
)


print("\n📊 CODE RESULT")
print("-" * 75)

print(
    final_state.get(
        "code_result",
        "No successful result"
    )
)


print("\nSTATUS:")
print(
    final_state.get(
        "final_status",
        "Unknown"
    )
)

print(
    "Attempts:",
    final_state.get(
        "retry_count",
        0
    )
)

"""real autonomous coding loop:

                    USER
                      ↓
                Planner Agent
                      ↓
              Data Analyst Agent
                      ↓
                Coding Agent
                      ↓
               Generate Code
                      ↓
                MCP Execute
                      ↓
                ┌───────────┐
                │  SUCCESS? │
                └─────┬─────┘
                  YES │ NO
                      │
              ┌───────┴────────┐
              ↓                ↓
         Continue       Debugging Agent
                               ↓
                          Fix Python
                               ↓
                         MCP Execute
                               ↓
                            SUCCESS?
                               ↓
                         Maximum 3 retries

Autonomous Debugging Agent

Test with an intentional error
"""

# =========================================================
# PART 6 — AUTONOMOUS DEBUGGING TEST
# =========================================================

faulty_code = """
result = df.groupby("Region")[
    "Crop_Yield_Tons_per_Hectare"
].mean()

# Intentional error
result = result.sort_values(by="Yield")
"""

print("❌ Testing intentionally faulty code...")
print(faulty_code)

# =========================================================
# EXECUTE FAULTY CODE THROUGH MCP
# =========================================================

error_output = await execute_code_with_mcp(
    faulty_code
)

print("\n")
print("=" * 70)
print("⚙️ MCP EXECUTION RESULT")
print("=" * 70)

print(error_output)

# =========================================================
# DEBUGGING AGENT
# =========================================================

debug_state = {

    "user_question":
        "Compare crop yield across regions.",

    "analysis_plan":
        """
        1. Group crop yield by region.
        2. Calculate average yield.
        3. Sort regions by yield.
        """,

    "generated_code":
        faulty_code,

    "error_message":
        error_output,

    "retry_count":
        0,

    "max_retries":
        3
}


debug_result = await debugging_agent(
    debug_state
)

fixed_code = debug_result["generated_code"]


print("\n")
print("=" * 70)
print("🛠️ DEBUGGING AGENT — CORRECTED CODE")
print("=" * 70)

print(fixed_code)

# =========================================================
# EXECUTE CORRECTED CODE THROUGH MCP
# =========================================================

fixed_output = await execute_code_with_mcp(
    fixed_code
)

print("\n")
print("=" * 70)
print("✅ CORRECTED CODE RESULT")
print("=" * 70)

print(fixed_output)

"""Root-Cause Analysis Agent

The Root-Cause Agent will take:

      Planner
        ↓
      Data Analyst
        ↓
      Coding Agent
        ↓
      MCP Execution
        ↓
      Successful Analysis Result
        ↓
      🔎 Root-Cause Agent

      Its job is not to blindly claim causation. It identifies the strongest potential contributing factors supported by the analysis.

Update State
"""

# =========================================================
# AGRODETECT AI — PART 7 STATE
# =========================================================

from typing import TypedDict


class AgroState(TypedDict, total=False):

    user_question: str

    analysis_plan: str

    dataset_summary: str
    statistics: str
    missing_values: str

    analysis: str

    generated_code: str
    code_result: str

    error_message: str

    retry_count: int
    max_retries: int

    final_status: str

    root_cause_analysis: str

"""Create Root-Cause Agent"""

# =========================================================
# ROOT-CAUSE ANALYSIS AGENT
# =========================================================

async def root_cause_agent(state: AgroState):

    print("\n🔎 ROOT-CAUSE ANALYSIS AGENT")
    print("Investigating potential agricultural factors...")

    question = state.get(
        "user_question",
        ""
    )

    plan = state.get(
        "analysis_plan",
        ""
    )

    analysis = state.get(
        "analysis",
        ""
    )

    code_result = state.get(
        "code_result",
        ""
    )

    statistics = state.get(
        "statistics",
        ""
    )

    prompt = f"""
You are the Root-Cause Analysis Agent
for AgroDetect AI.

USER QUESTION:
{question}

INVESTIGATION PLAN:
{plan}

DATA ANALYST FINDINGS:
{analysis}

PYTHON ANALYSIS RESULT:
{code_result}

DATASET STATISTICS:
{statistics}

Your task is to identify the strongest
potential factors associated with differences
in agricultural crop yield.

Requirements:

1. Identify the important findings.
2. Compare high-yield and low-yield patterns
   when supported by the data.
3. Identify potential contributing factors.
4. Rank the factors by importance when possible.
5. Clearly distinguish association from causation.
6. Do not invent numbers.
7. Do not claim that a factor caused the result
   unless the supplied analysis proves causation.
8. Give practical agricultural observations.

Return:

KEY FINDINGS
POTENTIAL CONTRIBUTING FACTORS
EVIDENCE
RECOMMENDATIONS
LIMITATIONS
"""

    response = llm.invoke(prompt)

    root_cause = response.content

    print("✅ Root-cause analysis completed")

    return {
        "root_cause_analysis": root_cause
    }

"""Test Root-Cause Agent"""

# =========================================================
# TEST ROOT-CAUSE AGENT
# =========================================================

test_state = {

    "user_question":
        "Why is crop yield lower in some regions?",

    "analysis_plan":
        final_state.get(
            "analysis_plan",
            ""
        ),

    "analysis":
        final_state.get(
            "analysis",
            ""
        ),

    "code_result":
        final_state.get(
            "code_result",
            ""
        ),

    "statistics":
        final_state.get(
            "statistics",
            ""
        )
}


root_result = await root_cause_agent(
    test_state
)


print("\n")
print("=" * 75)
print("🌾 AGRODETECT AI — ROOT-CAUSE ANALYSIS")
print("=" * 75)

print(
    root_result["root_cause_analysis"]
)

"""Add Root-Cause Agent to LangGraph"""

# =========================================================
# AGRODETECT LANGGRAPH — ROOT CAUSE
# =========================================================

from langgraph.graph import (
    StateGraph,
    START,
    END
)


graph_builder = StateGraph(AgroState)


# ---------------------------------------------------------
# Agents / Nodes
# ---------------------------------------------------------

graph_builder.add_node(
    "planner",
    planner_agent
)

graph_builder.add_node(
    "data_analyst",
    data_analyst_agent
)

graph_builder.add_node(
    "coding_agent",
    coding_agent
)

graph_builder.add_node(
    "execute_code",
    code_execution_node
)

graph_builder.add_node(
    "debugging_agent",
    debugging_agent
)

graph_builder.add_node(
    "root_cause",
    root_cause_agent
)


# ---------------------------------------------------------
# Main workflow
# ---------------------------------------------------------

graph_builder.add_edge(
    START,
    "planner"
)

graph_builder.add_edge(
    "planner",
    "data_analyst"
)

graph_builder.add_edge(
    "data_analyst",
    "coding_agent"
)

graph_builder.add_edge(
    "coding_agent",
    "execute_code"
)


# ---------------------------------------------------------
# Execution decision
# ---------------------------------------------------------

graph_builder.add_conditional_edges(

    "execute_code",

    debug_router,

    {
        "success": "root_cause",
        "debug": "debugging_agent",
        "stop": END
    }
)


# ---------------------------------------------------------
# Debug → Execute again
# ---------------------------------------------------------

graph_builder.add_edge(
    "debugging_agent",
    "execute_code"
)


# ---------------------------------------------------------
# Root Cause → END
# ---------------------------------------------------------

graph_builder.add_edge(
    "root_cause",
    END
)


agro_graph = graph_builder.compile()


print("✅ AgroDetect complete analysis graph created")

"""Run the complete workflow"""

# =========================================================
# RUN AGRODETECT AI — PART 7
# =========================================================

final_state = await agro_graph.ainvoke({

    "user_question":
        "Why is crop yield lower in some regions?",

    "retry_count": 0,

    "max_retries": 3
})


print("\n")
print("=" * 80)
print("🌾 AGRODETECT AI — ROOT-CAUSE REPORT")
print("=" * 80)


print("\n🧠 INVESTIGATION PLAN")
print("-" * 80)

print(
    final_state.get(
        "analysis_plan",
        "Not available"
    )
)


print("\n🔍 DATA ANALYSIS")
print("-" * 80)

print(
    final_state.get(
        "analysis",
        "Not available"
    )
)


print("\n👨‍💻 GENERATED CODE")
print("-" * 80)

print(
    final_state.get(
        "generated_code",
        "Not available"
    )
)


print("\n📊 CODE RESULT")
print("-" * 80)

print(
    final_state.get(
        "code_result",
        "Not available"
    )
)


print("\n🔎 ROOT-CAUSE ANALYSIS")
print("-" * 80)

print(
    final_state.get(
        "root_cause_analysis",
        "Not available"
    )
)


print("\nSTATUS")
print("-" * 80)

print(
    final_state.get(
        "final_status",
        "Unknown"
    )
)

"""USER
                        ↓
                  🧠 Planner
                        ↓
                🔍 Data Analyst
                        ↓
                 👨‍💻 Coding Agent
                        ↓
                   Generate Code
                        ↓
                   MCP Execute
                        ↓
                    Success?
                   ↙        ↘
                 NO          YES
                 ↓            ↓
          🛠️ Debug Agent   🔎 Root Cause
                 ↓            ↓
             Fix Code      Insights
                 ↓            ↓
             MCP Execute      ↓
                 └────────────┘
                        ↓
                  🌾 AgroDetect

| Agent               | Purpose                                 |
| ------------------- | --------------------------------------- |
| 🧠 Planner          | Decides what to investigate             |
| 🔍 Data Analyst     | Understands agricultural data           |
| 👨‍💻 Coding Agent  | Generates Python                        |
| 🛠️ Debugging Agent | Fixes failed Python                     |
| 🔎 Root-Cause Agent | Explains potential contributing factors |

Report Agent

Its job is to take all the work done by the previous agents and create one clean, user-friendly agricultural report.

Planner
        ↓
      Data Analyst
        ↓
      Coding Agent
        ↓
      MCP Execution
        ↓
      Debugging Agent ──→ if error
        ↓
      Root-Cause Agent
        ↓
      📝 Report Agent
        ↓
      FINAL REPORT

Update State
"""

# =========================================================
# AGRODETECT AI — PART 8 STATE
# =========================================================

from typing import TypedDict


class AgroState(TypedDict, total=False):

    user_question: str

    analysis_plan: str

    dataset_summary: str
    statistics: str
    missing_values: str

    analysis: str

    generated_code: str
    code_result: str

    error_message: str

    retry_count: int
    max_retries: int

    final_status: str

    root_cause_analysis: str

    final_report: str

"""Create Report Agent"""

# =========================================================
# REPORT AGENT
# =========================================================

async def report_agent(state: AgroState):

    print("\n📝 REPORT AGENT")
    print("Preparing final agricultural intelligence report...")

    question = state.get(
        "user_question",
        ""
    )

    analysis = state.get(
        "analysis",
        ""
    )

    code_result = state.get(
        "code_result",
        ""
    )

    root_cause = state.get(
        "root_cause_analysis",
        ""
    )

    prompt = f"""
You are the Report Agent of AgroDetect AI.

Create a clear professional agricultural intelligence report.

USER QUESTION:
{question}

DATA ANALYST FINDINGS:
{analysis}

PYTHON ANALYSIS RESULT:
{code_result}

ROOT-CAUSE ANALYSIS:
{root_cause}

Create the report using this structure:

# 🌾 AgroDetect AI Report

## 1. Question
State the user's question.

## 2. Key Findings
Give the most important findings.

## 3. Potential Contributing Factors
List the strongest factors supported by the analysis.

## 4. Evidence
Mention the relevant analysis results.

## 5. Recommendations
Give practical recommendations based only on the available evidence.

## 6. Limitations
Clearly mention that associations do not automatically prove causation.

Do not invent statistics.
Do not invent agricultural facts.
Keep the report concise and professional.
"""

    response = llm.invoke(prompt)

    final_report = response.content

    print("✅ Final report generated")

    return {
        "final_report": final_report
    }

"""Test Report Agent"""

# =========================================================
# TEST REPORT AGENT
# =========================================================

report_test_state = {

    "user_question":
        final_state.get(
            "user_question",
            "Why is crop yield lower in some regions?"
        ),

    "analysis":
        final_state.get(
            "analysis",
            ""
        ),

    "code_result":
        final_state.get(
            "code_result",
            ""
        ),

    "root_cause_analysis":
        final_state.get(
            "root_cause_analysis",
            ""
        )
}


report_result = await report_agent(
    report_test_state
)


print("\n")
print("=" * 80)
print("🌾 AGRODETECT AI — FINAL REPORT")
print("=" * 80)

print(
    report_result["final_report"]
)

"""Add Report Agent to LangGraph"""

# =========================================================
# AGRODETECT COMPLETE LANGGRAPH
# =========================================================

from langgraph.graph import (
    StateGraph,
    START,
    END
)


graph_builder = StateGraph(AgroState)


# ---------------------------------------------------------
# NODES
# ---------------------------------------------------------

graph_builder.add_node(
    "planner",
    planner_agent
)

graph_builder.add_node(
    "data_analyst",
    data_analyst_agent
)

graph_builder.add_node(
    "coding_agent",
    coding_agent
)

graph_builder.add_node(
    "execute_code",
    code_execution_node
)

graph_builder.add_node(
    "debugging_agent",
    debugging_agent
)

graph_builder.add_node(
    "root_cause",
    root_cause_agent
)

graph_builder.add_node(
    "report_agent",
    report_agent
)


# ---------------------------------------------------------
# MAIN FLOW
# ---------------------------------------------------------

graph_builder.add_edge(
    START,
    "planner"
)

graph_builder.add_edge(
    "planner",
    "data_analyst"
)

graph_builder.add_edge(
    "data_analyst",
    "coding_agent"
)

graph_builder.add_edge(
    "coding_agent",
    "execute_code"
)


# ---------------------------------------------------------
# SUCCESS / ERROR ROUTING
# ---------------------------------------------------------

graph_builder.add_conditional_edges(

    "execute_code",

    debug_router,

    {
        "success": "root_cause",
        "debug": "debugging_agent",
        "stop": END
    }
)


# ---------------------------------------------------------
# DEBUG → EXECUTE AGAIN
# ---------------------------------------------------------

graph_builder.add_edge(
    "debugging_agent",
    "execute_code"
)


# ---------------------------------------------------------
# ROOT CAUSE → REPORT
# ---------------------------------------------------------

graph_builder.add_edge(
    "root_cause",
    "report_agent"
)


# ---------------------------------------------------------
# REPORT → END
# ---------------------------------------------------------

graph_builder.add_edge(
    "report_agent",
    END
)


agro_graph = graph_builder.compile()

print("✅ Complete AgroDetect AI graph created")

"""Run the complete system"""

# =========================================================
# AGRODETECT AI — COMPLETE RUN
# =========================================================

final_state = await agro_graph.ainvoke({

    "user_question":
        "Why is crop yield lower in some regions?",

    "retry_count": 0,

    "max_retries": 3
})


print("\n")
print("=" * 80)
print("🌾🌾🌾 AGRODETECT AI — FINAL RESULT 🌾🌾🌾")
print("=" * 80)

print(
    final_state.get(
        "final_report",
        "Final report was not generated."
    )
)

"""Instead of showing all this:

Planner output,
Data Analyst output,
Python code,
MCP response,
Debugging information,
Root-cause analysis,

the final application can simply shown above

USER
                          │
                          ↓
                   🧠 PLANNER
                          │
                          ↓
                  🔍 DATA ANALYST
                          │
                          ↓
                   👨‍💻 CODING AGENT
                          │
                          ↓
                    MCP EXECUTION
                          │
                    ┌─────┴─────┐
                    ↓           ↓
                  ERROR       SUCCESS
                    ↓           │
              🛠️ DEBUGGER      │
                    ↓           │
                 RETRY          │
                    └─────┬─────┘
                          ↓
                   🔎 ROOT CAUSE
                          │
                          ↓
                     📝 REPORT
                          │
                          ↓
                         END

| # | Agent               | Job                                  |
| - | ------------------- | ------------------------------------ |
| 1 | 🧠 Planner          | Decides what to investigate          |
| 2 | 🔍 Data Analyst     | Understands the dataset              |
| 3 | 👨‍💻 Coding Agent  | Generates Python                     |
| 4 | 🛠️ Debugging Agent | Fixes failed code                    |
| 5 | 🔎 Root-Cause Agent | Finds potential contributing factors |
| 6 | 📝 Report Agent     | Creates the final report             |

Autonomous Visualization Agent

The system will automatically create useful charts from the analysis instead of us manually deciding which charts to make.

Add visualization fields
"""

# =========================================================
# AGRODETECT AI — PART 9 STATE
# =========================================================

from typing import TypedDict


class AgroState(TypedDict, total=False):

    user_question: str

    analysis_plan: str

    dataset_summary: str
    statistics: str
    missing_values: str

    analysis: str

    generated_code: str
    code_result: str

    error_message: str

    retry_count: int
    max_retries: int

    final_status: str

    root_cause_analysis: str

    chart_code: str
    chart_result: str

    final_report: str

"""Create MCP chart tool"""

# =========================================================
# MCP TOOL → CREATE AGRICULTURAL CHARTS
# =========================================================

import matplotlib.pyplot as plt


@mcp.tool()
def create_agricultural_chart(chart_type: str) -> str:
    """
    Create an agricultural analysis chart.

    Supported charts:
    - yield_by_region
    - rainfall_vs_yield
    - soil_moisture_vs_yield
    """

    try:

        data = pd.read_csv(CSV_PATH)

        plt.figure(figsize=(10, 6))

        # -------------------------------------------------
        # 1. Yield by Region
        # -------------------------------------------------

        if chart_type == "yield_by_region":

            values = (
                data.groupby("Region")
                ["Crop_Yield_Tons_per_Hectare"]
                .mean()
                .sort_values(ascending=False)
            )

            values.plot(kind="bar")

            plt.title(
                "Average Crop Yield by Region"
            )

            plt.xlabel("Region")
            plt.ylabel(
                "Crop Yield (Tons per Hectare)"
            )

            plt.xticks(rotation=45)

        # -------------------------------------------------
        # 2. Rainfall vs Yield
        # -------------------------------------------------

        elif chart_type == "rainfall_vs_yield":

            plt.scatter(
                data["Rainfall_mm"],
                data["Crop_Yield_Tons_per_Hectare"],
                alpha=0.6
            )

            plt.title(
                "Rainfall vs Crop Yield"
            )

            plt.xlabel(
                "Rainfall (mm)"
            )

            plt.ylabel(
                "Crop Yield (Tons per Hectare)"
            )

        # -------------------------------------------------
        # 3. Soil Moisture vs Yield
        # -------------------------------------------------

        elif chart_type == "soil_moisture_vs_yield":

            plt.scatter(
                data["Soil_Moisture_Percent"],
                data["Crop_Yield_Tons_per_Hectare"],
                alpha=0.6
            )

            plt.title(
                "Soil Moisture vs Crop Yield"
            )

            plt.xlabel(
                "Soil Moisture (%)"
            )

            plt.ylabel(
                "Crop Yield (Tons per Hectare)"
            )

        else:

            return (
                "ERROR: Unsupported chart type. "
                "Use yield_by_region, "
                "rainfall_vs_yield, or "
                "soil_moisture_vs_yield."
            )

        plt.tight_layout()

        filename = (
            f"/content/{chart_type}.png"
        )

        plt.savefig(
            filename,
            dpi=150,
            bbox_inches="tight"
        )

        plt.close()

        return f"SUCCESS: Chart created at {filename}"

    except Exception as e:

        return (
            f"ERROR: {type(e).__name__}: {str(e)}"
        )

"""Test the MCP chart tool"""

# =========================================================
# TEST MCP CHART
# =========================================================

async with Client(mcp) as client:

    result = await client.call_tool(
        "create_agricultural_chart",
        {
            "chart_type": "yield_by_region"
        }
    )

    print(result.content[0].text)

from IPython.display import Image, display

display(
    Image(
        filename="/content/yield_by_region.png"
    )
)

"""Create Visualization Agent"""

# =========================================================
# VISUALIZATION AGENT
# =========================================================

async def visualization_agent(state: AgroState):

    print("\n📊 VISUALIZATION AGENT")
    print("Creating agricultural charts...")

    chart_types = [
        "yield_by_region",
        "rainfall_vs_yield",
        "soil_moisture_vs_yield"
    ]

    results = []

    async with Client(mcp) as client:

        for chart_type in chart_types:

            result = await client.call_tool(
                "create_agricultural_chart",
                {
                    "chart_type": chart_type
                }
            )

            output = result.content[0].text

            results.append(
                f"{chart_type}: {output}"
            )

    chart_result = "\n".join(results)

    print("✅ Agricultural charts created")

    return {
        "chart_result": chart_result
    }

"""Test Visualization Agent"""

# =========================================================
# TEST VISUALIZATION AGENT
# =========================================================

visual_result = await visualization_agent(
    {
        "user_question":
            "Why is crop yield lower in some regions?"
    }
)

print("\n")
print("=" * 70)
print("📊 VISUALIZATION RESULTS")
print("=" * 70)

print(
    visual_result["chart_result"]
)

"""Display all charts"""

# =========================================================
# DISPLAY AGRICULTURAL CHARTS
# =========================================================

from IPython.display import Image, display

chart_files = [
    "/content/yield_by_region.png",
    "/content/rainfall_vs_yield.png",
    "/content/soil_moisture_vs_yield.png"
]

for chart_file in chart_files:

    # Create the chart if it doesn't exist
    chart_name = chart_file.split("/")[-1].replace(".png", "")

    if not os.path.exists(chart_file):

        async with Client(mcp) as client:

            await client.call_tool(
                "create_agricultural_chart",
                {
                    "chart_type": chart_name
                }
            )

    print("\n", chart_name)

    display(
        Image(
            filename=chart_file
        )
    )

"""        Add Visualization to LangGraph

        Root Cause
          ↓
        Visualization
          ↓
        Report
"""

# =========================================================
# AGRODETECT — PART 9 LANGGRAPH
# =========================================================

graph_builder = StateGraph(AgroState)


# ---------------------------------------------------------
# NODES
# ---------------------------------------------------------

graph_builder.add_node(
    "planner",
    planner_agent
)

graph_builder.add_node(
    "data_analyst",
    data_analyst_agent
)

graph_builder.add_node(
    "coding_agent",
    coding_agent
)

graph_builder.add_node(
    "execute_code",
    code_execution_node
)

graph_builder.add_node(
    "debugging_agent",
    debugging_agent
)

graph_builder.add_node(
    "root_cause",
    root_cause_agent
)

graph_builder.add_node(
    "visualization",
    visualization_agent
)

graph_builder.add_node(
    "report_agent",
    report_agent
)


# ---------------------------------------------------------
# MAIN FLOW
# ---------------------------------------------------------

graph_builder.add_edge(
    START,
    "planner"
)

graph_builder.add_edge(
    "planner",
    "data_analyst"
)

graph_builder.add_edge(
    "data_analyst",
    "coding_agent"
)

graph_builder.add_edge(
    "coding_agent",
    "execute_code"
)


# ---------------------------------------------------------
# ERROR / SUCCESS ROUTING
# ---------------------------------------------------------

graph_builder.add_conditional_edges(

    "execute_code",

    debug_router,

    {
        "success": "root_cause",
        "debug": "debugging_agent",
        "stop": END
    }
)


# ---------------------------------------------------------
# DEBUG → EXECUTE
# ---------------------------------------------------------

graph_builder.add_edge(
    "debugging_agent",
    "execute_code"
)


# ---------------------------------------------------------
# ROOT CAUSE → VISUALIZATION
# ---------------------------------------------------------

graph_builder.add_edge(
    "root_cause",
    "visualization"
)


# ---------------------------------------------------------
# VISUALIZATION → REPORT
# ---------------------------------------------------------

graph_builder.add_edge(
    "visualization",
    "report_agent"
)


# ---------------------------------------------------------
# REPORT → END
# ---------------------------------------------------------

graph_builder.add_edge(
    "report_agent",
    END
)


agro_graph = graph_builder.compile()

print("✅ AgroDetect Part 9 graph created")

"""Run the complete workflow"""

# =========================================================
# RUN AGRODETECT AI — PART 9
# =========================================================

final_state = await agro_graph.ainvoke({

    "user_question":
        "Why is crop yield lower in some regions?",

    "retry_count": 0,

    "max_retries": 3
})


print("\n")
print("=" * 80)
print("🌾 AGRODETECT AI — FINAL REPORT")
print("=" * 80)

print(
    final_state.get(
        "final_report",
        "Report not generated."
    )
)


print("\n")
print("=" * 80)
print("📊 CHARTS")
print("=" * 80)

print(
    final_state.get(
        "chart_result",
        "Charts not generated."
    )
)

"""USER
                          ↓
                   🧠 PLANNER
                          ↓
                  🔍 DATA ANALYST
                          ↓
                   👨‍💻 CODING AGENT
                          ↓
                    MCP EXECUTION
                          ↓
                       ERROR?
                     ↙       ↘
                   YES        NO
                    ↓          ↓
              🛠️ DEBUGGER     🔎 ROOT CAUSE
                    ↓          ↓
                 RETRY     📊 VISUALIZATION
                               ↓
                          📝 REPORT
                               ↓
                              END

| Agent                  | Responsibility                       |
| ---------------------- | ------------------------------------ |
| 🧠 Planner             | Creates investigation plan           |
| 🔍 Data Analyst        | Understands data                     |
| 👨‍💻 Coding Agent     | Generates Python                     |
| 🛠️ Debugging Agent    | Fixes failed code                    |
| 🔎 Root-Cause Agent    | Finds potential contributing factors |
| 📊 Visualization Agent | Creates charts                       |
| 📝 Report Agent        | Creates final report                 |
"""

!pip install -q -U gradio

# =========================================================
# AGRODETECT AI — GENERAL AGRICULTURAL CHATBOT
# =========================================================

async def agrodetect_chatbot(message, history):

    if not message or not message.strip():
        return "Please enter an agricultural question."

    print("\n" + "=" * 80)
    print("🌾 AGRODETECT AI")
    print("=" * 80)

    print("USER QUESTION:")
    print(message)

    try:

        # -------------------------------------------------
        # Run complete autonomous LangGraph workflow
        # -------------------------------------------------

        final_state = await agro_graph.ainvoke({

            "user_question": message.strip(),

            "retry_count": 0,

            "max_retries": 3
        })

        # -------------------------------------------------
        # Get final answer
        # -------------------------------------------------

        answer = final_state.get(
            "final_report",
            ""
        )

        if not answer:

            answer = final_state.get(
                "root_cause_analysis",
                ""
            )

        if not answer:

            answer = final_state.get(
                "analysis",
                ""
            )

        if not answer:

            answer = (
                "I could not generate an answer "
                "from the agricultural dataset."
            )

        print("\n✅ ANSWER GENERATED")

        return answer

    except Exception as e:

        print("\n❌ ERROR")
        print(str(e))

        return f"""
### ⚠️ AgroDetect AI Error

I could not complete the analysis.

**Error:** `{str(e)}`
"""

"""Create the Gradio UI"""

# =========================================================
# AGRODETECT AI — COMPATIBLE GRADIO UI
# =========================================================

import gradio as gr


demo = gr.ChatInterface(
    fn=agrodetect_chatbot,

    title="🌾 AgroDetect AI",

    description="""
Autonomous Agricultural Data Intelligence

Ask questions about crops, regions, soil, rainfall,
fertilizer, irrigation, temperature, pests, crop yield,
comparisons, statistics, and relationships.

Powered by Groq + LangChain + LangGraph + MCP
""",

    examples=[
        "How much crop yield is there in Tamil Nadu?",
        "Which region has the highest average crop yield?",
        "Which region has the lowest average crop yield?",
        "Which crop has the highest average yield?",
        "Which soil type has the highest crop yield?",
        "What is the average rainfall?",
        "How does rainfall relate to crop yield?",
        "How does soil moisture relate to crop yield?",
        "Does fertilizer usage relate to crop yield?",
        "Which irrigation type has the highest average yield?",
        "What are the minimum and maximum crop yields?",
        "Which region has the highest rainfall?",
        "Which crop is grown most frequently?",
        "Are there missing values in the dataset?",
        "Why is crop yield lower in some regions?",
        "Compare Tamil Nadu and Punjab crop yields.",
        "Give me the top 5 highest-yield regions.",
        "Give me the top 5 crops by average yield.",
        "What are the important factors associated with crop yield?"
    ],

    textbox=gr.Textbox(
        placeholder="Ask any question about the agricultural dataset..."
    )
)

print("✅ AgroDetect Gradio UI created")

# =========================================================
# LAUNCH AGRODETECT AI
# =========================================================

demo.launch(
    share=True,
    debug=True
)